@startuml Диаграмма состояний
title Диаграмма состояний: Удаление покупки
top to bottom direction
hide empty description
skinparam nodesep 65

[*] --> ГлавнаяСтраница : Открытие приложения

ГлавнаяСтраница --> ПросмотрПокупок : Выбор раздела "Просмотр покупок"
ПросмотрПокупок --> ДеталиПокупки : Выбор конкретной покупки
ДеталиПокупки --> ПодтверждениеУдаления : Нажатие кнопки "Удалить"
ПодтверждениеУдаления --> УспешноеУдаление : Подтверждение удаления
ПодтверждениеУдаления --> [*] : Отмена удаления

УспешноеУдаление --> ИсторияПокупок : Обновление истории покупок
УспешноеУдаление --> [*] : Возвращение к просмотру покупок

@enduml