@startuml Диаграмма состояний
title Диаграмма состояний: Удаление покупки
top to bottom direction
hide empty description
skinparam nodesep 65

[*] --> ГлавнаяСтраница : Открытие приложения

ГлавнаяСтраница --> ПросмотрПокупок : Выбор раздела "Просмотр покупок"
ПросмотрПокупок --> ДеталиПокупки : Выбор конкретной покупки
ДеталиПокупки --> ЗаявкаНаУдалениеОтправлена : Нажатие кнопки "Удалить"

ЗаявкаНаУдалениеОтправлена --> ИсторияПокупок : Обновление истории покупок
ЗаявкаНаУдалениеОтправлена --> [*] : Возвращение к просмотру покупок

@enduml